name: Build PDF

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  generate_pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Poetry
        run: |
          pip install poetry
          poetry install
      - name: Run build.py
        run: |
          poetry run python build.py
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Convert the markdown to a LaTeX pdf
        uses: docker://pandoc/latex:2.9
        with:
          args: >- # allows you to break string into multiple lines
            --from markdown
            --to latex
            --standalone
            --output constitution.pdf
            README.md
      - name: Upload the pdf
        uses: actions/upload-artifact@v2
        with:
          path: constitution.pdf
  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
      # this is just used to get repo info I think
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Download the pdf
        uses: actions/download-artifact@v2
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: artifact
